name: Deploy Created

on:
  release:
    types: created

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: deploy
        run: echo "deploying"
